blank_issues_enabled: false
contact_links:
  - name: ğŸ“š FAQs | å¸¸è§é—®é¢˜
    url: https://github.com/kvcache-ai/ktransformers/issues/1608
    about: Reading in advance is recommended | å»ºè®®æå‰é˜…è¯»